{
 "title": "ABTI HOME DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<center><table><td aling=\"center\" rowspan=\"4\" width=350><div class=\"text-center\"><a href=\"http://noc.abtitecnologia.com.br/zabbix/zabbix.php?action=map.view&sysmapid=5\" target=\"_blank\"><img src=\"http://www.abtitecnologia.com.br/wp-content/uploads/2018/06/cropped-logo-ABTEI.png\"></a></tr></td></table>"
  },
  { "title": "CURRENT DEVICE STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "HOSTS BY GROUP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT g.name, count(h.name) AS QTD, unix_timestamp(now()) as time_sec\nFROM hosts h \nJOIN hosts_groups hg ON h.hostid=hg.hostid \nJOIN hstgrp g ON hg.groupid = g.groupid \nWHERE h.status IN (0) AND NOT g.name=\"NULL\" \nGROUP BY g.name",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "mode": 4,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": false,
      "minSeverity": 0
     }
    }
   ]
  },
  {
   "title": "ZABBIX UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "ABTI" },
     "host": { "filter": "ZABBIX SERVER" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "NUMBER OF PROCESS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Processes" },
     "group": { "filter": "ABTI" },
     "host": { "filter": "ZABBIX SERVER" },
     "item": { "filter": "Number of processes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MONITORED SERVERS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Zabbix server" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Number of monitored hosts" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT count(host), unix_timestamp(now()) as time_sec  \r\nFROM hosts \r\nWHERE status <> (\"1\") AND available = 1 OR status = 0 AND host NOT IN (\"{#HV.UUID}\",\"{#VM.UUID}\") \r\nORDER BY status;\r\n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROBLEMS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "mode": 4,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 0,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "TOP  5  Triggers by Organization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT g.name, count(distinct e.eventid) as cnt_event, UNIX_TIMESTAMP(NOW()) as time_sec \nFROM triggers t INNER JOIN functions f ON ( f.triggerid = t.triggerid ) \nINNER JOIN items i ON ( i.itemid = f.itemid ) \nINNER JOIN hosts h ON ( i.hostid = h.hostid ) \nINNER JOIN events e ON ( e.objectid = t.triggerid ) \nINNER JOIN hosts_groups hg ON ( hg.hostid = h.hostid ) \nINNER JOIN hstgrp g ON ( g.groupid = hg.groupid ) \nWHERE e.clock>UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 30 day)) AND  t.flags IN ('0','4')\nGROUP BY g.name \nORDER BY cnt_event desc \nLIMIT 5;",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOP 5 Triggers by Host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT host, count(distinct e.eventid) as cnt_event, UNIX_TIMESTAMP(NOW()) as time_sec \r\nFROM triggers t \r\nINNER JOIN functions f ON ( f.triggerid = t.triggerid ) \r\nINNER JOIN items i ON ( i.itemid = f.itemid ) \r\nINNER JOIN hosts h ON ( i.hostid = h.hostid ) \r\nINNER JOIN events e ON ( e.objectid = t.triggerid ) \r\nINNER JOIN hosts_groups hg ON ( hg.hostid = h.hostid ) \r\nINNER JOIN hstgrp g ON ( g.groupid = hg.groupid ) \r\nWHERE e.clock>UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 30 day)) AND  t.flags IN ('0','4') \r\nGROUP BY host \r\nORDER BY cnt_event desc \r\nLIMIT 5;\r\n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}